# Docstrings for Flags and Intents generated by @discord_flags

@doc "Enables GUILD_CREATE, GUILD_UPDATE, GUILD_DELETE, GUILD_ROLE_*, CHANNEL_*, THREAD_*, STAGE_INSTANCE_* events." IntentGuilds
@doc "Enables GUILD_MEMBER_ADD, GUILD_MEMBER_UPDATE, GUILD_MEMBER_REMOVE, THREAD_MEMBERS_UPDATE events. **Privileged Intent**." IntentGuildMembers
@doc "Enables GUILD_AUDIT_LOG_ENTRY_CREATE, GUILD_BAN_ADD, GUILD_BAN_REMOVE events." IntentGuildModeration
@doc "Enables GUILD_EMOJIS_UPDATE, GUILD_STICKERS_UPDATE, GUILD_SOUNDBOARD_SOUND_* events." IntentGuildExpressions
@doc "Enables GUILD_INTEGRATIONS_UPDATE, INTEGRATION_CREATE, INTEGRATION_UPDATE, INTEGRATION_DELETE events." IntentGuildIntegrations
@doc "Enables WEBHOOKS_UPDATE events." IntentGuildWebhooks
@doc "Enables INVITE_CREATE, INVITE_DELETE events." IntentGuildInvites
@doc "Enables VOICE_STATE_UPDATE events." IntentGuildVoiceStates
@doc "Enables PRESENCE_UPDATE events. **Privileged Intent**." IntentGuildPresences
@doc "Enables MESSAGE_CREATE, MESSAGE_UPDATE, MESSAGE_DELETE, MESSAGE_DELETE_BULK events in guilds." IntentGuildMessages
@doc "Enables MESSAGE_REACTION_ADD, MESSAGE_REACTION_REMOVE, MESSAGE_REACTION_REMOVE_ALL, MESSAGE_REACTION_REMOVE_EMOJI events in guilds." IntentGuildMessageReactions
@doc "Enables TYPING_START events in guilds." IntentGuildMessageTyping
@doc "Enables MESSAGE_CREATE, MESSAGE_UPDATE, MESSAGE_DELETE, CHANNEL_PINS_UPDATE events in DMs." IntentDirectMessages
@doc "Enables MESSAGE_REACTION_ADD, MESSAGE_REACTION_REMOVE, MESSAGE_REACTION_REMOVE_ALL, MESSAGE_REACTION_REMOVE_EMOJI events in DMs." IntentDirectMessageReactions
@doc "Enables TYPING_START events in DMs." IntentDirectMessageTyping
@doc "Enables access to message content (content, embeds, attachments, components) in events. **Privileged Intent**." IntentMessageContent
@doc "Enables GUILD_SCHEDULED_EVENT_* events." IntentGuildScheduledEvents
@doc "Enables AUTO_MODERATION_RULE_* events." IntentAutoModerationConfiguration
@doc "Enables AUTO_MODERATION_ACTION_EXECUTION events." IntentAutoModerationExecution
@doc "Enables MESSAGE_POLL_VOTE_* events in guilds." IntentGuildMessagePolls
@doc "Enables MESSAGE_POLL_VOTE_* events in DMs." IntentDirectMessagePolls

@doc "All non-privileged intents combined." IntentAllNonPrivileged
@doc "All intents combined, including privileged ones." IntentAll

@doc "This message has been published to subscribed channels (via Channel Following)." MsgFlagCrossposted
@doc "This message originated from a message in another channel (via Channel Following)." MsgFlagIsCrosspost
@doc "Do not include any embeds when serializing this message." MsgFlagSuppressEmbeds
@doc "The source message for this crosspost has been deleted (via Channel Following)." MsgFlagSourceMessageDeleted
@doc "This message came from the urgent message system." MsgFlagUrgent
@doc "This message has an associated thread, with the same id as the message." MsgFlagHasThread
@doc "This message is only visible to the user who invoked the Interaction." MsgFlagEphemeral
@doc "This message is an Interaction Response and the bot is \"thinking\"." MsgFlagLoading
@doc "This message failed to mention some roles and add their members to the thread." MsgFlagFailedToMentionSomeRolesInThread
@doc "This message will not trigger push and desktop notifications." MsgFlagSuppressNotifications
@doc "This message is a voice message." MsgFlagIsVoiceMessage

@doc "Discord Employee" UserFlagStaff
@doc "Partnered Server Owner" UserFlagPartner
@doc "HypeSquad Events Member" UserFlagHypeSquad
@doc "Bug Hunter Level 1" UserFlagBugHunterLevel1
@doc "House Bravery Member" UserFlagHypeSquadBravery
@doc "House Brilliance Member" UserFlagHypeSquadBrilliance
@doc "House Balance Member" UserFlagHypeSquadBalance
@doc "Early Nitro Supporter" UserFlagEarlyNitroSupporter
@doc "User is a team" UserFlagTeamPseudoUser
@doc "Bug Hunter Level 2" UserFlagBugHunterLevel2
@doc "Verified Bot" UserFlagVerifiedBot
@doc "Early Verified Bot Developer" UserFlagVerifiedDeveloper
@doc "Moderator Programs Alumni" UserFlagCertifiedModerator
@doc "Bot uses only HTTP interactions and is shown in the online member list" UserFlagBotHTTPInteractions
@doc "Active Developer" UserFlagActiveDeveloper

@doc "Suppress member join notifications." SysChanSuppressJoinNotifications
@doc "Suppress server boost notifications." SysChanSuppressPremiumSubscriptions
@doc "Suppress server setup tips." SysChanSuppressGuildReminderNotifications
@doc "Suppress member join notification replies." SysChanSuppressJoinNotificationReplies
@doc "Suppress role subscription purchase and renewal notifications." SysChanSuppressRoleSubscriptionPurchaseNotifications
@doc "Suppress role subscription purchase and renewal notification replies." SysChanSuppressRoleSubscriptionPurchaseNotificationReplies

@doc "The channel is pinned in a forum." ChanFlagPinned
@doc "The channel requires tags (forums)." ChanFlagRequireTag
@doc "When set hides the embedded media download options." ChanFlagHideMediaDownloadOptions

@doc "Member has left and rejoined the guild." MemberFlagDidRejoin
@doc "Member has completed onboarding." MemberFlagCompletedOnboarding
@doc "Member is exempt from verification requirements." MemberFlagBypassesVerification
@doc "Member has started onboarding." MemberFlagStartedOnboarding
@doc "Member is a guest and can only access the guild through the channel they were invited to." MemberFlagIsGuest
@doc "Member has started home actions." MemberFlagStartedHomeActions
@doc "Member has completed home actions." MemberFlagCompletedHomeActions
@doc "Member's username is quarantined by automod." MemberFlagAutomodQuarantinedUsername
@doc "Member has acknowledged the DM settings upsell." MemberFlagDMSettingsUpsellAcknowledged

@doc "Role can be selected by members in an onboarding prompt." RoleFlagInPrompt

@doc "The attachment is a remix." AttachFlagIsRemix

@doc "SKU is available for purchase." SKUFlagAvailable
@doc "SKU is a guild subscription." SKUFlagGuildSubscription
@doc "SKU is a user subscription." SKUFlagUserSubscription
